backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: "product"
    label: "Product"
    folder: "src/pages/product2"
    create: true
    slug: "{{name}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "index-page",
        }
      - { label: Name, name: name, widget: string }
      - label: "Sections"
        name: "section"
        widget: "list"
        fields:
          - label: "ImageSection"
            name: "imageBlock"
            widget: "object"
            fields:
              - { label: Headline, name: headline, widget: string }
              - { label: Image, name: image, widget: image }
              - label: Type
                name: type
                widget: select
                options:
                  - { label: "Image on Left", value: "Left" }
                  - { label: "Image on Right", value: "Right" }
          - label: "ClientSection"
            name: "clientSection"
            widget: "object"
            fields:
              - { label: Name, name: name, widget: string }
      - widget: list
        name: sections
        label: Sections
        required: false
        hint: Page sections
        types:
          - name: blog_feed_section
            widget: object
            label: Blog Feed Section
            fields:
              - widget: string
                name: title
                label: Title
                required: false
                hint: The title of the section
              - widget: boolean
                name: show_recent
                label: Show recent posts
                required: true
                default: false
                hint: >-
                  Show the specified number of recent posts. Should not be used
                  with author and category filters.
              - widget: number
                name: recent_count
                label: Number of recent posts to show
                required: false
                valueType: int
              - widget: string
                name: author
                label: Author Filter
                required: false
                hint: Filter posts by an author
              - widget: string
                name: category
                label: Category Filter
                required: false
                hint: Filter posts by category
              - widget: hidden
                name: type
                label: Object Type
                required: true
                hint: The type of the object
                default: blog_feed_section
          - name: contact_section
            widget: object
            label: Contact Section
            fields:
              - widget: hidden
                name: type
                label: Object Type
                required: true
                hint: The type of the object
                default: contact_section
          - name: content_section
            widget: object
            label: Content Section
            fields:
              - widget: string
                name: title
                label: Title
                required: false
                hint: The title of the section
              - widget: markdown
                name: content
                label: Content
                required: false
                hint: The text content of the section
              - widget: hidden
                name: type
                label: Object Type
                required: true
                hint: The type of the object
                default: content_section
          - name: cta_section
            widget: object
            label: CTA Section
            fields:
              - widget: string
                name: title
                label: Title
                required: false
                hint: The title of the section
              - widget: string
                name: subtitle
                label: Subtitle
                required: false
                hint: The subtitle of the section
              - widget: list
                name: actions
                label: Action Buttons
                required: false
                fields:
                  - widget: string
                    name: label
                    label: Label
                    required: true
                  - widget: string
                    name: url
                    label: URL
                    required: true
                  - widget: select
                    name: style
                    label: Style
                    required: true
                    default: link
                    options:
                      - link
                      - primary
                      - secondary
                  - widget: boolean
                    name: new_window
                    label: Open in new tab/window
                    required: false
                    default: false
                  - widget: hidden
                    name: type
                    label: Object Type
                    required: true
                    hint: The type of the object
                    default: action
