backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8081/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ["192.168.0.1"]

media_folder: static/img
public_folder: /img

collections:
  - name: "landing"
    label: "Landing Page"
    folder: "src/pages/landing"
    create: true
    slug: "{{name}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "landing",
        }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - widget: list
        label: "Sections"
        name: "sections"
        required: false
        hint: Page Sections
        types:
          - name: introduction_section
            widget: object
            label: Introduction Section
            fields:
              - widget: string
                name: title
                label: Title
                required: false
                hint: The title of the section
              - widget: select
                name: color
                label: Color
                options:
                  - { label: "Red", value: "red" }
                  - { label: "Yellow", value: "yellow" }
              - widget: image
                name: image
                label: Intro Image
              - widget: text
                name: description
                label: Description
